.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH METACITY 1 "19 August 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
METACITY \- minimal GTK2 Window Manager
.SH SYNOPSIS
.B metacity
[\-\-sm\-disable] [\-\-sm\-save\-file=\fIFILENAME\fP] [\-\-display=\fIDISPLAY\fP] [\-\-replace]
.SH DESCRIPTION
This manual page documents briefly the
.B metacity\fP.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBmetacity\fP is a minimal X window manager that tries to be as crack free as possible. It supports sloppy focussing and multiple desktops.
.SH OPTIONS
.TP
.B \-\-sm\-disable
Disable the session management.
.TP
.B \-\-sm\-save\-file=FILENAME
Save a session to \fIFILENAME\fP.
.TP
.B \-\-display=DISPLAY
Connect to X display \fIDISPLAY\fP.
.TP
.B \-\-replace
a window manager which is running is replaced by \fBmetacity\fP.
.TP
.B \-h, \-\-help
Show summary of options.
.SH SEE ALSO
.BR metacity-message (1)
.SH AUTHOR
This manual page was written by Akira TAGOH <tagoh@debian.org>,
for the Debian GNU/Linux system (but may be used by others). The original manual page was written by Thom May <thom@debian.org>.
