#!/usr/bin/python3
#
# Copyright (C) 2018 Georges Basile Stavracas Neto <gbsneto@gnome.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.


from gi.repository import GLib, Gio

import argparse
import sys


def start_profiler(seconds):
    proxy = Gio.DBusProxy.new_for_bus_sync(
        Gio.BusType.SESSION,
        Gio.DBusProxyFlags.DO_NOT_AUTO_START,
        None,
        'org.gnome.Mutter.IdleMonitor',
        '/org/gnome/Mutter/Profiler',
        'org.gnome.Sysprof.Capturer',
        None)

    params = GLib.Variant('(a{sv})', ({
        'timeout': GLib.Variant('u', seconds),
    }, ))

    print(params)

    result = proxy.call_sync('Capture', params, 0, 10000, None)
    print(result)


def main():
    """Sets various options and runs the auxiliary helper."""
    parser = argparse.ArgumentParser(description='Profile Mutter with Sysprof')
    parser.add_argument('seconds', type=int,
                        help="Timeout (in seconds) to capture data")

    args = parser.parse_args()

    print(args.seconds)

    start_profiler(args.seconds)

    return 0

if __name__ == '__main__':
    sys.exit(main())

