#!/bin/bash

[ $# -ne 1 ] && exit 1

if [ -n $PKEXEC_UID -a $(id -u) -eq 0 ]; then
    exec >& /tmp/backtrace.$PKEXEC_UID.$(date +%N)

    cd /proc/$1/task
    for thread in *; do
        echo "Thread ${thread}:"
        cat $thread/stack
    done
    exit 0
fi
